CXX = g++
CXXFLAGS = -Wall -std=c++11
TARGET = execution_scheduling
SRC = execution_scheduling_demo.cpp

${TARGET} : ${SRC}
	${CXX} ${CXXFLAGS} ${SRC} -o ${TARGET}

.PHONY : clean
clean:
	rm -f ${TARGET}
